### ISSUE TITLE
Basic Modifications to UI

### ISSUE THREAD

**Issue by rajdesai17** [programmerftw/100x-date#2]
![Screenshot 2024-12-06 225326](https://github.com/user-attachments/assets/479f7818-06d9-4c60-b3c6-f2b8f81d7bec)
![Screenshot 2024-12-06 225341](https://github.com/user-attachments/assets/a298eb5b-5350-4dd5-a696-6107844c6dcc)
# UI Enhancements and New Features Added

Tried doing some basic modifications to UI, Do check and revert back.

1. **Header Component**
   - Added a new fixed header with glass-morphism effect
   - Implemented notification system with unread counter
   - Added profile dropdown menu with "View My Profile" option

2. **Profile Form Improvements**
   - Reorganized layout with profile photo at the top
   - Added "What are you looking for?" section
   - Added favorite programming language selection
   - Enhanced form fields with hover animations and glow effects

3. **Visual Enhancements**
   - Implemented cyberpunk-inspired color scheme
   - Added gradient text effects for headings
   - Enhanced hover states and animations
   - Improved card designs with glass-morphism effects

4. **Notification System**
   - Added notification bell with unread counter
   - Implemented dropdown for notification history
   - Added match notifications with timestamps
   - Notifications persist until read

**Comment by programmerftw** [comment]
pretty cool bhai! now chota sa work if u can go through ki when u open that card carousel from that i button toh there we can add 4 photos right, toh uske neeche add a bio field which can store only 40 words! then will merge ur PR!

**Comment by rajdesai17** [comment]
That alex profile is of other user right? So It'll show the photos and about that photo that was added while creating the profile. Did i get this right?
Here - 
![Screenshot 2024-12-07 092552](https://github.com/user-attachments/assets/4a328c73-5f3e-45a5-9b51-fc65c5066624)

**Comment by programmerftw** [comment]
yes u did it right mere bhai! Pr raise krdu
